CREATE TABLE IF NOT EXISTS players (
  id       TEXT PRIMARY KEY,
  name     TEXT NOT NULL,
  attack   INTEGER NOT NULL DEFAULT 5,
  defense  INTEGER NOT NULL DEFAULT 5,
  physical INTEGER NOT NULL DEFAULT 5,
  morale   INTEGER NOT NULL DEFAULT 5
);
